name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Elixir
        uses: erlef/setup-elixir@v1
        with:
          elixir-version: '1.16.2'
          otp-version: '26.0'

      - name: Compile the app
        run: make compile

      - name: Release master
        run: make release_master

      - name: Release agent
        run: make release_agent

      - name: Upload Release agent
        uses: actions/upload-artifact@v2
        with:
          name: agent
          path: _build/prod/agent-0.1.0.tar.gz

      - name: Upload Release master
        uses: actions/upload-artifact@v2
        with:
          name: master
          path: _build/prod/master-0.1.0.tar.gz
